### PR TITLE
Create Backend Api 

### PR DESCRIPTION
**Pull request by ankitt26**
In this PR, I did-
- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Set up Postgres database.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from table

### CODE REVIEW

**Comment by ankitt26** [comment]
_Note: Run the command_ `rails server -p 3005`

**Comment by ankitt26** [comment]
_Note: Run the command_ `rails server -p 3005` to start the server.

**Comment by ankitt26** [comment]
_Note: Run the command_ `rails server -p 3005` _to start the server._

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @ankitt26👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Good job with the Hello World project. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
